sample_rate: 16000
frame_size_ms: 10 # 10ms only

speech_data_paths:
    - "/path/to/LibriSpeech/train-clean-100/"

noise_data_paths:
    - "/path/to/urban8k/"
    - "/path/to/ESC-50-master/audio/"

test_speech_data_paths:
    - "/path/to/LibriSpeech/dev-clean/"

submission_data_paths:
    - "/path/to/for_devs/"

model: "lenet32" # lenet32, cnn_bilstm, ensemble_lenet32_cnn_bilsm
# For ensemble model specify array of checkpoints!
ckpt_path: "checkpoints/path/to/chekpoint.ckpt"
continue_from_ckpt: false
epochs: 50
batch_size: 32
num_workers: 2
log_every_n_step: 150
val_check_interval: 0.1

wandb:
    project: "vad_test"
    name: "as_model" # if 'as_model' then name will be taken from 'model' parameter
    mode: "online" # online or disabled
    test_name: "Benchmark" # name for testing script
    submission_name: "Submission" # (+ model name) name for submission script

seed: 42

external_vad: "webrtc"  # webrtc or cobra (cobra turned out to be really bad for 10ms frame size)
cobra_threshold: 0.7

test_models:
    - model: "webrtc"
      ckpt_path: ""
    - model: "lenet32"
      ckpt_path: "checkpoints/path/to/lenet32.ckpt"
    - model: "cnn_bilstm"
      ckpt_path: "checkpoints/path/to/cnn_bilstm.ckpt"
    - model: "ensemble_lenet32_cnn_bilstm"
      ckpt_path:
          - "checkpoints/path/to/lenet32.ckpt"
          - "checkpoints/path/to/cnn_bilstm.ckpt"

submission_thresholds:
    - 0.5
    - 0.63
    - 0.7
    - 0.8
    - 0.9
    - 0.95
    - 0.98
