sample_rate: 16000
frame_size_ms: 10 # 10ms only
frame_size: int(sample_rate * (frame_size_ms / 1000.0))
device: "cuda"

speech_data_paths:
    - "/path/to/LibriSpeech/train-clean-100/"

noise_data_paths:
    - "/path/to/urban8k/"
    - "/path/to/ESC-50-master/audio/"

model: "cnn_bilstm" # naive_linear, lenet8, lenet32, cnn_bilstm
continue_from_ckpt: true
ckpt_path: "checkpoints/path/to/chekpoint.ckpt"
epochs: 50
batch_size: 32
num_workers: 2
log_every_n_step: 150
val_check_interval: 0.3

wandb:
    project: "vad_test"
    name: "as_model" # if 'as_model' then name will be taken from 'model' parameter
    mode: "online" # online or disabled

seed: 42

external_vad: "webrtc"  # webrtc or cobra (cobra turned out to be really bad for 10ms frame size)
cobra_threshold: 0.7

test_models:
    - model: "webrtc"
      ckpt_path: ""
    - model: "lenet32"
      ckpt_path: ""
    - model: "cnn_bilstm"
      ckpt_path: "checkpoints/YceP2pCR/last.ckpt"
